# Generated by Django 3.1.4 on 2020-12-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
