# Generated by Django 3.1.4 on 2020-12-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0004_superhero_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='comic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='food',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
